In [5]:
import pandas as pd
df = pd.read_csv("stations.csv")
df.head()

,StationId,StationName,City,State,Status
0,AP001,"Secretariat, Amaravati - APPCB",Amaravati,Andhra Pradesh,Active
1,AP002,"Anand Kala Kshetram, Rajamahendravaram - APPCB",Rajamahendravaram,Andhra Pradesh,NaN
2,AP003,"Tirumala, Tirupati - APPCB",Tirupati,Andhra Pradesh,NaN
3,AP004,"PWD Grounds, Vijayawada - APPCB",Vijayawada,Andhra Pradesh,NaN
4,AP005,"GVM Corporation, Visakhapatnam - APPCB",Visakhapatnam,Andhra Pradesh,Active

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StationId    230 non-null    object
 1   StationName  230 non-null    object
 2   City         230 non-null    object
 3   State        230 non-null    object
 4   Status       133 non-null    object
dtypes: object(5)
memory usage: 9.1+ KB

In [7]:
df.shape

(230, 5)

In [8]:
df.isnull().sum()

StationId       0
StationName     0
City            0
State           0
Status         97
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

In [11]:
df.columns

Index(['StationId', 'StationName', 'City', 'State', 'Status'], dtype='object')

In [12]:
df.describe(include='all')

       StationId                     StationName   City  State  Status
count        230                             230    230    230     133
unique       230                             230    127     21       2
top        AP001  Secretariat, Amaravati - APPCB  Delhi  Delhi  Active
freq           1                               1     38     38     131

In [13]:
df['City'].nunique()

127

In [14]:
df['City'].value_counts().head(10)

City
Delhi        38
Mumbai       10
Bengaluru    10
Kolkata       7
Patna         6
Hyderabad     6
Lucknow       5
Noida         4
Faridabad     4
Ghaziabad     4
Name: count, dtype: int64

In [16]:
df.to_csv("stations_cleaned.csv",index=False)